repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args:
          - --fix=auto
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies:
          [
            pytest,
            types-pillow,
            "pydantic[dotenv]==1.10.11",
            numpy,
            torch,
            types-requests,
            types-xmltodict,
            types-tqdm,
            loguru,
            pytorch-lightning,
            mlflow
          ]
        args: [--config-file, pyproject.toml]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
