repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args:
          - --fix=auto
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: setup
        name: setup
        entry: poetry install --dry-run
        language: system
        types: [python]
        pass_filenames: false

      - id: check
        name: check
        entry: poetry check
        language: system
        types: [python]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: poetry run mypy --config-file pyproject.toml
        language: system
        types: [python]

      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        language: system
        types: [python]

      - id: flake8
        name: flake8
        entry: poetry run flake8 --config .flake8
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
