[project]
name = "minecraft-copilot-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markupsafe==2.1.3",
    "mpi4py>=4.0.3",
    "nbtlib>=2.0.4",
    "torch>=2.7.0",
    "torchaudio>=2.7.0",
    "torchcfm",
    "torchvision>=0.22.0",
]

[tool.uv.sources]
torchcfm = { git = "https://github.com/atong01/conditional-flow-matching.git" }

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu128"
