[project]
name = "minecraft-copilot-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "torch>=2.0.0",
  "nbtlib>=2.0.0",
  "tqdm>=4.65.0",
  "matplotlib>=3.7.0",
  "scikit-learn>=1.2.0",
  "markupsafe==2.1.3",
  "torchvision>=0.22.0",
  "torchaudio>=2.7.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu128"
