[tool.poetry]
name = "minecraft-copilot-ml"
version = "0.1.0"
description = ""
authors = ["DemyCode <verycols@gmail.com>"]
readme = "README.md"
packages = [{ include = "minecraft_copilot_ml" }]

[tool.poetry.dependencies]
python = "^3.10"
torch = "2.0.0"
selenium = "^4.9.1"
nbtlib = { git = "https://github.com/DemyCode/nbtlib.git", branch = "main" }
pandas = "^2.0.1"
tqdm = "^4.65.0"
scikit-learn = "^1.2.2"
mlflow = "2.5.0"
boto3 = "^1.26.146"
boto3-stubs = { extras = ["essential"], version = "^1.26.146" }
types-requests = "^2.31.0.1"
loguru = "^0.7.0"
types-tqdm = "^4.65.0.1"
types-xmltodict = "^0.13.0.2"
pydantic = "2.5.3"
pytorch-lightning = "2.0.4"
pydantic-settings = "^2.1.0"
beautifulsoup4 = "^4.12.3"

[tool.poetry.group.dev.dependencies]
ipympl = "^0.9.3"
pre-commit = "^3.3.2"
black = "^23.3.0"
flake8 = "^6.0.0"
ipykernel = "^6.23.0"
mypy = "^1.3.0"
pytest = "^7.3.1"
coverage = "^7.2.7"
matplotlib = "^3.7.1"
pytest-watch = "^4.2.0"
pytest-testmon = "^2.0.8"
isort = "^5.13.2"

[tool.black]
line-length = 120

[tool.mypy]
exclude = ['.venv']
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true

[tool.coverage.run]
source = ["minecraft_copilot_ml"]

[tool.isort]
profile = "black"
line_length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
