name: Dispatcher

on:
  push:

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/action-github-app-token@v2.0.0
        id: generate-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: ${{ github.repository }}/minecraft-copilot
          event-type: dispatcher
          client-payload: '{"branch": "${{ github.ref }}"}'
