name: Main pipeline

on:
  push:
    branches:
      - master

concurrency:
  group: master-${{ github.ref }}

jobs:
  validation:
    uses: ./.github/workflows/pull_request.yml

  build:
    runs-on: ubuntu-latest
    needs: validation
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: minecraft-copilot-ml
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest || echo 'The image does not exist yet.'
        docker build --cache-from $ECR_REGISTRY/$ECR_REPOSITORY:latest -t minecraft-copilot-ml .
        docker tag minecraft-copilot-ml $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        if [ ${{ github.ref }} = 'refs/heads/master' ]; then
          docker tag minecraft-copilot-ml $ECR_REGISTRY/$ECR_REPOSITORY:latest
        fi
        docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

  train:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-3

    - name: Run training
      run: |
        aws sagemaker create-training-job --training-job-name minecraft-copilot-ml-${{ github.sha }} \
          --algorithm-specification 'TrainingImage=$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }},TrainingInputMode=File,TrainingImageConfig={TrainingRepositoryAccessMode=Vpc}' \
          --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/service-role/AmazonSageMaker-ExecutionRole-20230601T201737 \
          --output-data-config S3OutputPath=s3://minecraft-copilot-ml-training-job/${{ github.sha }} \
          --resource-config InstanceCount=1,InstanceType=ml.m5.large,VolumeSizeInGB=1 \
          --stopping-condition MaxRuntimeInSeconds=7200 \
          --vpc-config Subnets=subnet-0790a43a46eb79dfc,subnet-09c39b225dc62dc66,subnet-05ee5401ebbba5686,SecurityGroupIds=sg-021242b98d384f4bf
