name: Validation pipeline

on:
  pull_request:
    branches:
      - master
  workflow_call:
    secrets:
      GH_APP_ID:
        required: true
      GH_APP_KEY:
        required: true

concurrency:
  group: pull_request-${{ github.ref }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/action-github-app-token@v2.0.0
        id: generate-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - run: poetry install
      - run: poetry run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/action-github-app-token@v2.0.0
        id: generate-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - run: poetry install
      - run: poetry run coverage run -m pytest -v
      # - run: poetry run coverage report -m --fail-under 100
      - run: poetry run coverage html -d ${{ github.head_ref || github.ref_name }} 
      - run: git checkout gh-pages
      - run: git add ${{ github.head_ref || github.ref_name }}
      - run: git commit -m "Add coverage report for ${{ github.head_ref || github.ref_name }}"
      - run: git push origin gh-pages

