name: Validation pipeline

on:
  pull_request:
    branches:
      - master
  workflow_call:
    secrets:
      GH_APP_ID:
        required: true
      GH_APP_KEY:
        required: true

concurrency:
  group: pull_request-${{ github.ref }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/action-github-app-token@v2.0.0
        id: generate-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install poetry
      - run: poetry export --dev -f requirements.txt --output requirements.txt --without-hashes
      - run: pip install -r requirements.txt
      - run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/action-github-app-token@v2.0.0
        id: generate-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install poetry
      - run: poetry export --dev -f requirements.txt --output requirements.txt --without-hashes
      - run: pip install -r requirements.txt
      - run: coverage run -m pytest -v
      - run: coverage report -m --fail-under 100
